<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MD0BEV7" failures="0" tests="14" name="CaseManagement.ValidatingNavigation" time="50.828" errors="1" timestamp="21 Jan 2025 14:02:55 GMT">
  <testcase classname="CaseManagement.ValidatingNavigation" name="navigationToCompletedCasePageFromDashboardTest" time="0.568"/>
  <testcase classname="CaseManagement.ValidatingNavigation" name="caseLIstFilerTest" time="0.015"/>
  <testcase classname="CaseManagement.ValidatingNavigation" name="navigationToDashboardPageFromCompletedCaseTest" time="0.911"/>
  <testcase classname="CaseManagement.ValidatingNavigation" name="navigationToGisPageFromDashboardTest" time="1.951"/>
  <testcase classname="CaseManagement.ValidatingNavigation" name="verifyCaseById" time="8.005">
    <error message="text did not match the expected value. expected [CASE-00096] but found [CM-00467]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: text did not match the expected value. expected [CASE-00096] but found [CM-00467]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at CaseManagement.ValidatingNavigation.verifyCaseById(ValidatingNavigation.java:366)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- verifyCaseById -->
  <testcase classname="CaseManagement.ValidatingNavigation" name="navigationToGISPageFromCompletedCaseTest" time="0.156"/>
  <testcase classname="CaseManagement.ValidatingNavigation" name="navigatingToApplicationTest" time="15.852"/>
  <testcase classname="CaseManagement.ValidatingNavigation" name="validateUserOnCasesModuleTest" time="3.899"/>
  <testcase classname="CaseManagement.ValidatingNavigation" name="navigationToDashboardFromCaseListPageTest" time="2.838"/>
  <testcase classname="CaseManagement.ValidatingNavigation" name="searchRegionInGIS" time="9.580"/>
  <testcase classname="CaseManagement.ValidatingNavigation" name="validateUserOnDashboardTest" time="2.306"/>
  <testcase classname="CaseManagement.ValidatingNavigation" name="navigationToCompletedPageFromGisTest" time="1.417"/>
  <testcase classname="CaseManagement.ValidatingNavigation" name="validateUserOnCasesListModuleTest" time="2.700"/>
  <testcase classname="CaseManagement.ValidatingNavigation" name="navigationTodashboardPageFromGisTest" time="0.630"/>
</testsuite> <!-- CaseManagement.ValidatingNavigation -->
